algo = input('Digite algo: ')
print('Tipo: ', type(algo))
print('Tem número: ', algo.isnumeric())
print('Tem letra: ', algo.isalpha())
print('É alfanúmerico: ', algo.isalnum())
print('Tem espaço: ', algo.isspace())
print('Tem letras maiusculas: ', algo.isupper())
print('Tem letra  minuscula: ', algo.islower())
print('Está capitalizada: ', algo.istitle())

