print(input.__doc__)
#help(print)
""" 		HELP() -> FUNÇÃO INTERNA (MÉTODO)
		NO PROMPT DE COMANDO DO PYTHON DIRETAMENTE DO CODADOR OU DA PROPRIA MAQUINA.
		
		PARA ENTRAR DIGITE: PYTHON E DEPOIS HELP() E DEPOIS A FUNÇÃO OU BIBLIOTECA QUE A PESSOA PRECISA, ASSIM NÃO PRECISANDO ACESSAR A BIBLIOTECA DO PYTHON, POIS JÁ TERA A MSM DIRETAMENTE NO PROMPT
		
PARA SAIR DIGITE: QUIT OU Q """